use_frameworks!
target 'klStringUtilities-Demo' do
	platform :ios, '11.0'
	pod "klStringUtilities"
end

target 'klStringUtilities-iOSTests' do
	platform :ios, '11.0'
	pod "klStringUtilities"
end



target 'klStringUtilities-tvOSTests' do
	platform :tvos, '11.0'
	pod "klStringUtilities"
end
